<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Додати',
    'Category' => 'Категорія',
    'Language' => 'Мова',
    'List translation' => '',
    'Translation' => 'Переклад',
    'all' => 'всі',
    'source' => 'Исходник',
    'Add new category' => 'Додати нову категорію',
    'Select category' => 'Оберіть категорію',
    'select' => 'оберить',
    'or write new' => 'або введіть нову',
    'text' => 'текст',
    'Filter' => 'Фільтр',
    'Filter the' => 'Фільтрувати',
    'Languages' => 'Мови'
];
